### ISSUE TITLE
Error when installing requirements

### ISSUE THREAD

**Issue by raphant** [TheWeirdlings/TwitchTube#6] opened 2017-08-12 00:33 UTC
I am getting a `IOError: [Errno 21] Is a directory: '/tmp/pip-build-2srBIc/get/setup.py'`
when running pip install -r requirements.txt. 
Seems to be related to this code 
`return open(os.path.join(os.path.dirname(__file__), fname)).read()`

**Comment by TheHollidayInn** [comment] 2017-08-12 06:18
Thanks for reporting. Can you tell me what OS are you on and are you using a virtual environment?

**Comment by raphant** [comment] 2017-08-12 15:54
Thanks for your response. 
I'm using Ubuntu 16.04 and I'm using the Python 2.7 Virtual Environment.

**Comment by raphant** [comment] 2017-08-12 16:18
However, I was able to go around that problem by installing each file manually. Later, after running `sudo pip install -e .` I was able to install the program. Now there are only a couple of things that need to be updated:
1. client_secrets.json needs to be in the `Phaseout` folder as that is where the `generator.py` is located before generator can be run.
2. `Helpers.py` was located in the Workers but not in 'phaseout'. generator.py needs helpers.py to run.

Were these files intended to be moved up to the root directory?

Thank you.

**Comment by raphant** [comment] 2017-08-12 16:22
After I moved the files to the appropriate locations, I was able to run the 
`python phaseout/generator.py --actio
n=create --item=bot --noauth_local_webserver` 
command and ran into the error:
`File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 13 column 5 (char 511)`

I will update this if I find a way around this.

**Comment by TheHollidayInn** [comment] 2017-08-12 22:08
I think the issue is I need to package the generator better. I can't remember if I was intentionally trying to remove the generator or not now.. Sadly. I was moving towards the workers which was a different architecture then my original implementation.

What do you mean by "installing each file manually"? Do you mean you installed the packages manually?

I will be able to run through this flow tomorrow and update. Thanks for the help.

**Comment by raphant** [comment] 2017-08-13 15:55
Okay, that makes sense now. Thanks for the response, a couple of things:

1. The generator.py being in the phaseout folder may point to you being in the processes of removing the generator.
2. To answer your question about installing the files, you are right, I meant I installed each _package_ manually. 
3. I see that you are utilizing both Mongo and Redis, is it possible that you were trying to phase one of those out too? If so which one?

**Comment by TheHollidayInn** [comment] 2017-08-13 16:15
Great thanks! I'm about to work on this, so I'll update you with the process.

Also, I am using Redis for cache/quick transactions. So, the queue system and chat is managed there. I use mongo for long term items like the bots and commands. This is a common pattern to use a memory-based db and a disk based db.

**Comment by raphant** [comment] 2017-08-13 16:18
Ah, I see. Alright then, good luck.

**Comment by TheHollidayInn** [comment] 2017-08-13 16:47
Alright, I have added a PR: https://github.com/TheWeirdlings/TwitchTube/pull/7. The new instructions are in the Readme. Can you see if those work better for you?

**Closed as completed** 2017-08-30 15:21 UTC
